<Project>
  <PropertyGroup>
    <Version>0.7.0</Version>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <Deterministic>true</Deterministic>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <FileVersion>$(Version).0</FileVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <InformationalVersion>$(Version)-gaming-edition</InformationalVersion>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
