namespace Dismode.Contracts.Commands;

public enum CommandKind
{
    GetComponentStatus = 1,
    DiscoverSystem = 2,
    StartOptimizationSession = 3,
    ApproveOptimizationPlan = 4,
    RestoreOptimizationSession = 5,
    StopApprovedService = 6,
    SetProcessPriority = 7,
    SetProcessEcoQos = 8,
    ActivateManagedPowerProfile = 9,
    GetActiveSession = 10,
    CloseGame = 11,
    ShutdownComponents = 12,
    SetFrameRateTracking = 13,
    GetSystemOptimizerStatus = 14,
    GetHardwareFingerprint = 15,
    GetSystemTweakCatalog = 16,
    PrepareSystemExperiment = 17,
    AdvanceSystemExperiment = 18,
    SavePerGameOptimizationProfile = 19,
    SaveGlobalOptimizationProfile = 20,
    RestoreSystemOptimization = 21,
    GetSystemOptimizationHistory = 22,
    PrepareSystemOptimizerUpdate = 23,
    SubmitBenchmarkCapture = 24,
    SetSystemOptimizerConsent = 25,
    GetSystemOptimizationProfiles = 26,
    ActivatePerGameOptimizationProfile = 27,
    RestorePerGameOptimizationProfile = 28,
}
